package com.cloudsync.model.enums;

public enum SyncPhase {
    FETCHING_METADATA, PERSISTING_METADATA, COMPARING, AWAITING_CONFIRMATION, DOWNLOADING, GENERATING_THUMBNAILS, DONE, ERROR, CANCELLED, REORGANIZING
}
